---
kind: pipeline
type: docker
name: default

steps:
  - name: ping
    image: redis
    commands:
      - sleep 5
      - redis-cli -h cache ping

services:
  - name: cache
    image: redis

---
kind: signature
hmac: 9240a3ecc30b71acad1e0ae33818dd7d7055ed23603a59e07738fb5d88371fbf

...
