---
kind: pipeline
type: docker
name: default

steps:
  - name: cache
    image: redis
    detach: true

  - name: ping
    image: redis
    commands:
      - sleep 5
      - redis-cli -h cache ping
# services:
#   - name: cache
#     image: redis

---
kind: signature
hmac: b347ba509b66bcd4857981e1793c9faf6348b45e3063fa93ba647bae8cb7e0ff

...
