version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: dummy.sh
  AfterInstall:
    - location: dummy.sh
  ApplicationStart:
    - location: dummy.sh
  ApplicationStop:
    - location: dummy.sh
